### ISSUE TITLE
broadcasting/auth 403 error

### ISSUE THREAD

**Issue by 4n70w4** [CoreProc/nova-notification-feed#11]
Hi! I do everything according to the instructions, but the real-time event reception does not work. Events come only during the reloading of the page.

I found one defect. Need use:

```php
Broadcast::channel('users.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});
```

Instead from instruction:

```php
Broadcast::channel('App.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});
```

403 error is fixed.

But in real time no messages are received.
There are no errors in the browser console and server logs.
Any idea what could be wrong?

Nova 2.0.6

**Comment by josespinal** [comment]
You just saved the day! Thank you for that.

**Comment by chrisbjr** [comment]
Hi @4n70w4 could have been an error in your config/env variables as you said in your previous issue

**Comment by Delaney** [comment]
@chrisbjr @4n70w4 my Nova model is `AdminUser` in namespace `App`. None of the methods seems to be working for me
