### ISSUE TITLE
It only get new notifications when the page refresh

### ISSUE THREAD

**Issue by miharbi** [CoreProc/nova-notification-feed#24]
Hi I followed all the steps and everything is ok, but it only get new notifications when the page refresh,  I'm trying in my local environment , there is no errors, only those warnings : 

![Screenshot from 2019-11-21 12-05-20](https://user-images.githubusercontent.com/770449/69354481-efed8000-0c5e-11ea-8221-ea30e8fe735d.png)

Does anyone has any advice?

**Comment by Delaney** [comment]
@miharbi hello, please were you able to solve this issue?

**Comment by miharbi** [comment]
> @miharbi hello, please were you able to solve this issue?

Hi, that was long ago, I don't remember but check on your Laravel CORS configuration

**Comment by Delaney** [comment]
> > @miharbi hello, please were you able to solve this issue?
> 
> Hi, that was long ago, I don't remember but check on your Laravel CORS configuration

Hey, still no luck. I don't even get the console warnings. Do I have to add something to my CORS config?
