### ISSUE TITLE
Support for laravel-websockets

### ISSUE THREAD

**Issue by einardivision** [CoreProc/nova-notification-feed#3]
Hi

Great package, been trying to get it working with [laravel-websockets](
https://github.com/beyondcode/laravel-websockets). It seems that there is only a minor change needed to make it work.

It needs to point to **another websockets server, normally on port 6001** and then there is some **auth routes also included** with the package for laravel. The echo client seems to support changing of these variables so you can connect to your own websockets server without **Pusher** :)

I am having trouble because i have to copy the vue components and change them and reimport them. Would be really nice if you could make the vue components publishable so i don't have to have my own :+1: 

Any assistance would be greatly appreciated! Have a nice day

**Comment by chrisbjr** [comment]
Definitely in the roadmap. Coming soon.

**Comment by chrisbjr** [comment]
Hi @einardivision just tagged `v1.1.0`. This adds the ability to support laravel-websockets and hopefully other configs as well. Will add to readme about this soon.
