### ISSUE TITLE
Dropdown missing

### ISSUE THREAD

**Issue by Jam0r85** [CoreProc/nova-notification-feed#5]
Latest version of Nova, following the instructions and added the required includes in the new layout.blade.php file and the dropdown doesn't appear?

Tried clearing cache and views.

Echo is working as it's displayed in console.

**Comment by chrisbjr** [comment]
Hi, can you paste the contents of your layout.blade.php?

**Comment by Jam0r85** [comment]
`<!DOCTYPE html>
<html lang="en" class="h-full font-sans antialiased">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=1280">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    @include('nova-echo::meta')

    <title>{{ Nova::name() }}</title>

    
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,800,800i,900,900i" rel="stylesheet">

    
    <link rel="stylesheet" href="{{ mix('app.css', 'vendor/nova') }}">

    
    @foreach(Nova::availableStyles(request()) as $name => $path)
        <link rel="stylesheet" href="/nova-api/styles/{{ $name }}">
    @endforeach
</head>
<body class="min-w-site bg-40 text-black min-h-full">
<div id="nova">
    <div v-cloak class="flex min-h-screen">
        
        <div class="min-h-screen flex-none pt-header min-h-screen w-sidebar bg-grad-sidebar px-6">
            <a href="{{ Nova::path() }}">
                <div class="absolute pin-t pin-l pin-r bg-logo flex items-center w-sidebar h-header px-6 text-white">
                    @include('nova::partials.logo')
                </div>
            </a>

            @foreach (Nova::availableTools(request()) as $tool)
                {!! $tool->renderNavigation() !!}
            @endforeach
        </div>

        
        <div class="content">
            <div class="flex items-center relative shadow h-header bg-white z-20 px-6">
                <a v-if="'{{ Nova::name() }}'" href="{{ Config::get('nova.url') }}" class="no-underline dim font-bold text-90 mr-6">
                    {{ Nova::name() }}
                </a>

                @if (count(Nova::globallySearchableResources(request())) > 0)
                    <global-search></global-search>
                @endif

                <dropdown class="ml-auto h-9 flex items-center dropdown-right">
                    @include('nova::partials.user')
                </dropdown>

                @include('nova_notification_feed::notification_feed')
            </div>

            <div data-testid="content" class="px-view py-view mx-auto">
                @yield('content')

                @include('nova::partials.footer')
            </div>
        </div>
    </div>
</div>

<script>
    window.config = @json(Nova::jsonVariables(request()));
</script>


<script src="{{ mix('manifest.js', 'vendor/nova') }}"></script>
<script src="{{ mix('vendor.js', 'vendor/nova') }}"></script>
<script src="{{ mix('app.js', 'vendor/nova') }}"></script>


<script>
    window.Nova = new CreateNova(config)
</script>


@foreach (Nova::availableScripts(request()) as $name => $path)
    @if (starts_with($path, ['http://', 'https://']))
        <script src="{!! $path !!}"></script>
    @else
        <script src="/nova-api/scripts/{{ $name }}"></script>
    @endif
@endforeach


<script>
    Nova.liftOff()
</script>
</body>
</html>
`

Thats placed in resources/views/vendor/nova/layout.blade.php

**Comment by Jam0r85** [comment]
Sorry about the copy n paste, trying to get it to display correctly but hope you get the idea.

**Comment by Jam0r85** [comment]
I can see the component when viewing the source so it's being included, just nothing visible.

**Comment by chrisbjr** [comment]
@Jam0r85 were you able to solve this? not sure how to replicate this.

**Comment by Jam0r85** [comment]
Sorted it!

Not sure how but it's working.

I had my own NovaNotifications component which I removed, updated composer and bingo the dropdown appeared? Very odd.

**Comment by Jinandra** [comment]
Hi chrisbjr, it's really good component you have create and really help.

But I need help regarding if I wana to use different table and need to do some changes in your code. How can i proceed?

**Comment by Jinandra** [comment]
If possible please reply ASAP. Thanks
