### ISSUE TITLE
Cannot read property 'complete' of undefined

### ISSUE THREAD

**Issue by Naoray** [CoreProc/nova-notification-feed#6]
I am using this pkg in combination with laravel-websockets. The configuration of the laravel-websockets seems to work, since I can use the DebugDashboard and connect to my websocket server just fine. However, everytime I open any nova page I get the following error:

![image](https://user-images.githubusercontent.com/10154100/53812014-d7b3c480-3f5a-11e9-8260-0d88f00d36f8.png)

I am not sure if it might be that my channel is not setup the right way?

```php
// routes/channel.php
Broadcast::channel('MShule.Models.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});

// MShule\Models\User
    public function receivesBroadcastNotificationsOn()
    {
        return 'MShule.Models.User.{id}';
    }
```

Would be super nice if you can give me some hints on where I can look to get rid of this error @chrisbjr ?!

**Comment by Naoray** [comment]
I just deleted the `receivesBroadcastNotificationsOn` method and started the worker with `queue:work` (forgot this one, so I didn't see any processing notifications before) :see_no_evil:

**Comment by chrisbjr** [comment]
@Naoray glad you figured it out!
