### ISSUE TITLE
Cannot read property 'complete' of undefined

### ISSUE THREAD

**Issue by shalawani** [CoreProc/nova-notification-feed#8]
![screenshot_1](https://user-images.githubusercontent.com/7045417/53882908-a5709880-4028-11e9-90a8-5530ed174ae4.png)

any hints please ?

**Comment by wa7eedem** [comment]
I have the same one .

<img width="718" alt="Screen Shot 2019-03-19 at 10 30 34 PM" src="https://user-images.githubusercontent.com/1952412/54636089-ad075700-4a96-11e9-9c1f-1b42f501dd16.png">

**Comment by chrisbjr** [comment]
Hi @shalawani @wa7eedem, I remember running into this before. I recall it was an issue because I was missing a config. I can't recall what the specific configuration was, I'll try to recreate it.

**Comment by hedyharto** [comment]
do we have any solution for this?

**Comment by hedyharto** [comment]
Hi guys, i think i found the solution. Remove toDate() from function toArray() on NotificationResource.php

**Comment by phuclh** [comment]
@chrisbjr do you have any solutions for that? Thank you!

**Comment by phuclh** [comment]
This errors get fixed by adding this line in the `head` tag

`@include('nova-echo::meta')`

**Comment by AndreyGrin** [comment]
I have the same issue and it looks like the problem in receive notification function.
![Screenshot_2](https://user-images.githubusercontent.com/2453346/61780888-0815d580-ae0c-11e9-979b-99fcc8de4996.png)

**Comment by Naoray** [comment]
Can confirm this... Allthough I receive notifications, I am still getting this error shown on the console on page load

**Comment by mydnic** [comment]
I have the same problem.
I'm not really looking to use the broadcasting feature, I only want to list notification in there at page load. But it doesn't work because of this issue

Any solution ?

**Comment by Naoray** [comment]
Have already created a PR...

**Comment by chrisbjr** [comment]
Hi @Naoray did your recent PR fix this as well?

**Comment by chrisbjr** [comment]
Hi all, just pushed a fix for this. Will the new release as v1.3.1
